"""add vote counter

Revision ID: e44ee6c77be4
Revises: 2573081d12db
Create Date: 2025-01-07 00:33:29.332849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44ee6c77be4'
down_revision: Union[str, None] = '2573081d12db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('vote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'vote_count')
    # ### end Alembic commands ###
